### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by smooJitter** [apollostack/apollo-server-tutorial#2]
On my mac I get this

```
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./server.js`
GraphQL Server is now running on http://localhost:8080

/Users/dwaynecole/React_Boilers/apollo-server-tutorial-master/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by helfer** [comment]
Do you have a mongoDB server running on that port? If there's no server running, then the app will crash when it tries to connect to it. Could be fixed with a PR where the server works fine, except for the `views` field, which requires the MongoDB server.

**Comment by smooJitter** [comment]
Hello.  Yes, I do have Mongo installed but I haven't tried running and independent mongo session.  My bad.  I'll give it a shot. Like meteor, I thought it would take care of the mongo stuff.   Thanks and I'll let you know

**Comment by helfer** [comment]
@smooJitter: I assume this is fixed now. If not, please feel free to reopen.

**Comment by jingxingxingzhi** [comment]
@smooJitter 
I have similar problem. Could you describe how you fix it? Thanks a lot!

**Comment by helfer** [comment]
@jingxingxingzhi You need to install and launch mongodb. If it's running, you should be able to connect to a mongo shell by typing `mongo` in the commandline.
